# This is a basic workflow to help you get started with Actions

name: BuildWeb

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  workflow_dispatch:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: martipello/flutter-action@v2
        with:
          channel: stable # or: beta, master (or main)
      - run: flutter --version
      - run: flutter pub get
      - run: flutter build web
